name: CI/CD for Shopping Online

on:
  push:
    branches:
      - main

jobs:
  server_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies and build server
      working-directory: server
      run: |
        npm install
        npm run build  # Adjust this command to your server's build process

  admin_client_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies and build admin client
      working-directory: client-admin
      run: |
        npm install
        npm run build  # Adjust this command to your admin client's build process

  customer_client_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies and build customer client
      working-directory: client-customer
      run: |
        npm install
        npm run build  # Adjust this command to your customer client's build process

  deploy:
    needs: [server_build, admin_client_build, customer_client_build]
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Admin Client to Azure
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_BEACH_0C543C300 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/admin"  
        api_location: "server"  
        app_build_command: ""  
        api_build_command: ""  
        app_artifact_location: "client-admin/build"
        output_location: ""  

    - name: Deploy Customer Client to Azure
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_MUD_051D49200 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"  # Adjust as needed
        api_location: "/server"  # Leave empty for client
        app_build_command: ""  # Leave empty for client
        api_build_command: ""  # Leave empty for client
        app_artifact_location: "client-customer/build"  # Adjust as needed
        output_location: ""  # Leave empty for default

    # - name: Deploy Customer Client to Azure
    #   uses: Azure/static-web-apps-deploy@v1
    #   with:
    #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     action: "upload"
    #     app_location: "/customer"  # Adjust as needed
    #     api_location: ""  # Leave empty for client
    #     app_build_command: ""  # Leave empty for client
    #     api_build_command: ""  # Leave empty for client
    #     app_artifact_location: "client-customer/build"  # Adjust as needed
    #     output_location: ""  # Leave empty for default
